baseurl: '/system-design'

plugins:
  - jekyll-seo-tag
  - jekyll-feed
  - jekyll-paginate
  - jekyll-sitemap
  - jekyll-gist
  - jemoji
  - jekyll-include-cache
  - jekyll-target-blank
  - jekyll-loading-lazy
  - jekyll-gzip
  # - jekyll-compress-images
  # - amp-jekyll
